export default [
  {
    id: 1,
    postedOn: new Date(),
    title: "Frontend Developer",
    type: "Full time",
    location: "Remote",
    experience: "Junior Level",
    companyName: "Google",
    companyUrl: "https://google.com",
    skills: ["Javascript", "React.js", "Node.js"],
    link: "https://google.com/careers",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "Backend Developer",
    type: "Part time",
    location: "Office",
    experience: "Fresher",
    companyName: "Yahoo",
    companyUrl: "https://www.yahoo.com/",
    skills: ["Angular", "Node.js"],
    link: "https://yahoo.com/jobs",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "Designer",
    type: "Part Time",
    location: "Remote",
    experience: "Junior Level",
    companyName: "Oracle",
    companyUrl: "https://www.oracle.com/",
    skills: ["flutter"],
    link: "https://www.oracle.com/careers",
  },
  {
    id: 5,
    postedOn: new Date(),
    title: "Andriod Developer",
    type: "Part Time",
    location: "Remote",
    experience: "Junior Level",
    companyName: "Facebook",
    companyUrl: "https://www.facebook.com",
    skills: ["flutter"],
    link: "https://facebook.com/careers",
  },
  {
    id: 6,
    postedOn: new Date(),
    title: "Mobile dev",
    type: "Contract",
    location: "Remote",
    experience: "Full Time",
    companyName: "Facebook",
    companyUrl: "https://www.facebook.com",
    skills: ["flutter"],
    link: "https://facebook.com/careers",
  },
  {
    id: 7,
    postedOn: new Date(),
    title: "Mobile dev",
    type: "Contract",
    location: "Remote",
    experience: "Full Time",
    companyName: "Facebook",
    companyUrl: "https://www.facebook.com",
    skills: ["flutter"],
    link: "https://facebook.com/careers",
  },
  {
    id: 8,
    postedOn: new Date(),
    title: "Mobile dev",
    type: "Contract",
    location: "Remote",
    experience: "Full Time",
    companyName: "Facebook",
    companyUrl: "https://www.facebook.com",
    skills: ["flutter"],
    link: "https://facebook.com/careers",
  },
  {
    id: 9,
    postedOn: new Date(),
    title: "Mobile dev",
    type: "Contract",
    location: "Remote",
    experience: "Full Time",
    companyName: "Facebook",
    companyUrl: "https://www.facebook.com",
    skills: ["flutter"],
    link: "https://facebook.com/careers",
  },
  {
    id: 10,
    postedOn: new Date(),
    title: "Mobile dev",
    type: "Contract",
    location: "Remote",
    experience: "Full Time",
    companyName: "Facebook",
    companyUrl: "https://www.facebook.com",
    skills: ["flutter"],
    link: "https://facebook.com/careers",
  },
  {
    id: 11,
    postedOn: new Date(),
    title: "Mobile dev",
    type: "Contract",
    location: "Remote",
    experience: "Full Time",
    companyName: "Facebook",
    companyUrl: "https://www.facebook.com",
    skills: ["flutter"],
    link: "https://facebook.com/careers",
  },
  {
    id: 12,
    postedOn: new Date(),
    title: "Mobile dev",
    type: "Contract",
    location: "Remote",
    experience: "Full Time",
    companyName: "Facebook",
    companyUrl: "https://www.facebook.com",
    skills: ["flutter"],
    link: "https://facebook.com/careers",
  },
];
